<!DOCTYPE html>
<html lang="en">
<head><title>Pwa Preview</title></head>
<body>
<div id="app"></div>
</body>
<script>
    window.appEndpoint = "https://pwa-cdn.publisherstoolbox.com";
    function getParameterByName(e,t){t||(t=window.location.href),e=e.replace(/[\[\]]/g,"\\$&");var n=new RegExp("[?&]"+e+"(=([^&#]*)|&|#|$)").exec(t);return n?n[2]?decodeURIComponent(n[2].replace(/\+/g," ")):"":null}function buildRules(e){return e.map(function(e){return{name:e[0],rule:e[1]}})}var widthViewport=Math.max(document.documentElement.clientWidth,window.innerWidth||0);if(!getParameterByName("noapp")&&widthViewport<=1024){var fetch_text=function(e){return fetch(e).then(function(e){return e.text()})},nodeName=function(e,t){return e.nodeName&&e.nodeName.toUpperCase()===t.toUpperCase()},evalScript=function(e,t){var n=e.text||e.textContent||e.innerHTML||"",o=document.getElementsByTagName("head")[0]||document.documentElement,r=document.createElement("script");r.type="text/javascript",e.id&&(r.id=e.id),e.src&&(r.src=e.src),r.setAttribute("async",""),r.appendChild(document.createTextNode(n)),o.insertBefore(r,t.firstChild),e.parentNode&&e.parentNode.removeChild(e)},gatherScripts=function(e,t){for(var n=0;e[n];n++)!t||!nodeName(e[n],"script")||e[n].type&&"text/javascript"!==e[n].type.toLowerCase()&&"application/json"!==e[n].type.toLowerCase()||t.push(e[n])},getHeadScripts=function(e){var t=document.getElementById("total-custom-scripts");if(t)try{for(var n=parseInt(t.value),o=0;o<n;o++){var r=document.getElementById("pwa-custom-script-"+o);r&&e.push(r)}}catch(e){console.warn(e)}};fetch_text(window.appEndpoint).then(function(e){document.getElementById("app").innerHTML=e;var t=[],n=document.getElementById("next-scripts");var o=document.getElementById("social-scripts"),r=document.getElementById("re-scripts"),c=document.getElementById("pwa-custom-scripts"),a=n.childNodes[0].childNodes,i=o.childNodes[0].childNodes;if(gatherScripts(a,t),gatherScripts(i,t),c){var d=c.childNodes;gatherScripts(d,t)}for(var s in getHeadScripts(t),n.innerHTML="",o.innerHTML="",t.reverse())evalScript(t[s],r);"function"==typeof pwaPostInjector&&setTimeout(function(){return pwaPostInjector()},3e3)}).catch(function(e){console.warn(e)})}function setLocalThemeAction(e){return{type:"SET_LOCAL_THEME_CHANGES",payload:{appTheme:e}}}function updateThemeLocal(e){if("undefined"!=typeof window&&window.__NEXT_REDUX_STORE__){var t=JSON.parse(e);window.__NEXT_REDUX_STORE__.dispatch(setLocalThemeAction(t))}}function bindEvent(e,t,n){e.addEventListener?e.addEventListener(t,n,!1):e.attachEvent&&e.attachEvent("on"+t,n)}bindEvent(window,"message",function(a){if(a.data){var e=JSON.parse(a.data);"PtPwaTheme"===e["@type"]&&updateThemeLocal(JSON.stringify(e))}});
</script>
</html>
